source "http://rubygems.org"

gem "bson_ext"
gem "coffee-script"
gem "haml"
gem "heroku"
gem "mongo_mapper"
gem "pusher"
gem "rack-proxy"
gem "racksh"
gem "sass"
gem "sinatra"
gem "sinatra-twitter-oauth"
gem "sprockets"
gem "twitter_oauth"
